name: PiSCAT Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  piscat-test:
    name: ${{matrix.os}} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [MacOS, Ubuntu, Windows]
        python-version: ['3.8', '3.10']
        exclude:
          - os: MacOS
            python-version: '3.8'
    env:
      DISPLAY: :0 # Tell Xvfb which virtual display to use.
      QT_DEBUG_PLUGINS: 1 # Improve Qt debugging experience.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Set up Xvfb
        if: runner.os == "Linux"
        run: |
          sudo apt-get install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libopengl0 libegl1-mesa
          sudo Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Setup Python Environment
        run: |
          python -m pip install --upgrade pip pipenv setuptools wheel
          python -m pip install -e .[test]
      - name: Run Test Suite
        run: |
          pytest tests/Module/InputOutput/cpu_configurations_test.py
