name: PiSCAT Linux Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0 # For Xvfb
      QT_DEBUG_PLUGINS=1 # For Qt Debugging
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Set up Xvfb
        run: |
          sudo apt-get install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libopengl0 libegl1-mesa
          sudo Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
          pip freeze
      - name: Run Test Suite
        run: |
          uname -a
          ulimit -a
          free -h
          pwd
          tree .
          python --version
          pytest tests/Module/InputOutput/cpu_configurations_test.py
